"""Add email notification preferences

Revision ID: 1cd37ddfc236
Revises: 0b6eed4e2b28
Create Date: 2025-09-07 18:15:51.905699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cd37ddfc236'
down_revision: Union[str, Sequence[str], None] = '0b6eed4e2b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_notifications_events', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('users', sa.Column('email_notifications_messages', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('email_notifications_newsletter', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_notifications_newsletter')
    op.drop_column('users', 'email_notifications_messages')
    op.drop_column('users', 'email_notifications_events')
    # ### end Alembic commands ###
