"""add_message_system

Revision ID: 48c44d68e290
Revises: 8728ff40a224
Create Date: 2025-09-06 12:37:38.714264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c44d68e290'
down_revision: Union[str, Sequence[str], None] = '8728ff40a224'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('messages_enabled', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('messages_from_strangers', sa.Boolean(), server_default='1', nullable=False))
    op.add_column('users', sa.Column('messages_notifications', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'messages_notifications')
    op.drop_column('users', 'messages_from_strangers')
    op.drop_column('users', 'messages_enabled')
    # ### end Alembic commands ###
