"""Add enhanced service fields

Revision ID: 9fb01f10c65b
Revises: 0ed3dd511156
Create Date: 2025-09-16 11:29:00.653914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb01f10c65b'
down_revision: Union[str, Sequence[str], None] = '0ed3dd511156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('services', sa.Column('service_image_url', sa.String(length=500), nullable=True))
    op.add_column('services', sa.Column('meeting_locations', sa.JSON(), nullable=True))
    op.add_column('services', sa.Column('view_count', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('interest_count', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('is_completed', sa.Boolean(), nullable=False))
    op.add_column('services', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('services', sa.Column('price_type', sa.String(length=50), nullable=True))
    op.add_column('services', sa.Column('price_amount', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('price_currency', sa.String(length=3), nullable=False))
    op.add_column('services', sa.Column('estimated_duration_hours', sa.Float(), nullable=True))
    op.add_column('services', sa.Column('contact_method', sa.String(length=50), nullable=False))
    op.add_column('services', sa.Column('response_time_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('services', 'response_time_hours')
    op.drop_column('services', 'contact_method')
    op.drop_column('services', 'estimated_duration_hours')
    op.drop_column('services', 'price_currency')
    op.drop_column('services', 'price_amount')
    op.drop_column('services', 'price_type')
    op.drop_column('services', 'completed_at')
    op.drop_column('services', 'is_completed')
    op.drop_column('services', 'interest_count')
    op.drop_column('services', 'view_count')
    op.drop_column('services', 'meeting_locations')
    op.drop_column('services', 'service_image_url')
    op.drop_column('services', 'updated_at')
    # ### end Alembic commands ###
