GENRES = {
    "fiction": {"name_de": "Belletristik", "name_en": "Fiction", "icon": "📖"},
    "non_fiction": {"name_de": "Sachbuch", "name_en": "Non-Fiction", "icon": "📚"},
    "biography": {"name_de": "Biografie", "name_en": "Biography", "icon": "👤"},
    "history": {"name_de": "Geschichte", "name_en": "History", "icon": "🏛️"},
    "philosophy": {"name_de": "Philosophie", "name_en": "Philosophy", "icon": "🤔"},
    "psychology": {"name_de": "Psychologie", "name_en": "Psychology", "icon": "🧠"},
    "science": {"name_de": "Wissenschaft", "name_en": "Science", "icon": "🔬"},
    "technology": {"name_de": "Technik", "name_en": "Technology", "icon": "💻"},
    "arts": {"name_de": "Kunst", "name_en": "Arts", "icon": "🎨"},
    "sports": {"name_de": "Sport", "name_en": "Sports", "icon": "⚽"},
    "travel": {"name_de": "Reise", "name_en": "Travel", "icon": "✈️"},
    "cooking": {"name_de": "Kochen", "name_en": "Cooking", "icon": "🍳"},
    "self_help": {"name_de": "Ratgeber", "name_en": "Self-Help", "icon": "💡"},
    "religion": {"name_de": "Religion", "name_en": "Religion", "icon": "🙏"},
    "business": {"name_de": "Wirtschaft", "name_en": "Business", "icon": "💼"},
    "children": {"name_de": "Kinderbuch", "name_en": "Children", "icon": "👶"},
}


LANGUAGES = {
    # Deutsch
    "de": "Deutsch",
    "ger": "Deutsch",
    "deu": "Deutsch",
    "german": "Deutsch",
    # Englisch
    "en": "Englisch",
    "eng": "Englisch",
    "english": "Englisch",
    # Französisch
    "fr": "Französisch",
    "fre": "Französisch",
    "fra": "Französisch",
    "french": "Französisch",
    # Spanisch
    "es": "Spanisch",
    "spa": "Spanisch",
    "spanish": "Spanisch",
    # Italienisch
    "it": "Italienisch",
    "ita": "Italienisch",
    "italian": "Italienisch",
    # Niederländisch
    "nl": "Niederländisch",
    "dut": "Niederländisch",
    "nld": "Niederländisch",
    "dutch": "Niederländisch",
    # Portugiesisch
    "pt": "Portugiesisch",
    "por": "Portugiesisch",
    "portuguese": "Portugiesisch",
    # Russisch
    "ru": "Russisch",
    "rus": "Russisch",
    "russian": "Russisch",
    # Chinesisch
    "zh": "Chinesisch",
    "chi": "Chinesisch",
    "zho": "Chinesisch",
    "chinese": "Chinesisch",
    # Japanisch
    "ja": "Japanisch",
    "jpn": "Japanisch",
    "japanese": "Japanisch",
    # Koreanisch
    "ko": "Koreanisch",
    "kor": "Koreanisch",
    "korean": "Koreanisch",
    # Arabisch
    "ar": "Arabisch",
    "ara": "Arabisch",
    "arabic": "Arabisch",
    # Hindi
    "hi": "Hindi",
    "hin": "Hindi",
    "hindi": "Hindi",
    # Polnisch
    "pl": "Polnisch",
    "pol": "Polnisch",
    "polish": "Polnisch",
    # Türkisch
    "tr": "Türkisch",
    "tur": "Türkisch",
    "turkish": "Türkisch",
    # Schwedisch
    "sv": "Schwedisch",
    "swe": "Schwedisch",
    "swedish": "Schwedisch",
    # Norwegisch
    "no": "Norwegisch",
    "nor": "Norwegisch",
    "norwegian": "Norwegisch",
    # Dänisch
    "da": "Dänisch",
    "dan": "Dänisch",
    "danish": "Dänisch",
    # Finnisch
    "fi": "Finnisch",
    "fin": "Finnisch",
    "finnish": "Finnisch",
    # Griechisch
    "el": "Griechisch",
    "gre": "Griechisch",
    "ell": "Griechisch",
    "greek": "Griechisch",
    # Hebräisch
    "he": "Hebräisch",
    "heb": "Hebräisch",
    "hebrew": "Hebräisch",
    # Tschechisch
    "cs": "Tschechisch",
    "ces": "Tschechisch",
    "cze": "Tschechisch",
    "czech": "Tschechisch",
    # Ungarisch
    "hu": "Ungarisch",
    "hun": "Ungarisch",
    "hungarian": "Ungarisch",
    # Rumänisch
    "ro": "Rumänisch",
    "ron": "Rumänisch",
    "rum": "Rumänisch",
    "romanian": "Rumänisch",
    # Bulgarisch
    "bg": "Bulgarisch",
    "bul": "Bulgarisch",
    "bulgarian": "Bulgarisch",
    # Kroatisch
    "hr": "Kroatisch",
    "hrv": "Kroatisch",
    "croatian": "Kroatisch",
    # Serbisch
    "sr": "Serbisch",
    "srp": "Serbisch",
    "serbian": "Serbisch",
    # Slowakisch
    "sk": "Slowakisch",
    "slk": "Slowakisch",
    "slo": "Slowakisch",
    "slovak": "Slowakisch",
    # Slowenisch
    "sl": "Slowenisch",
    "slv": "Slowenisch",
    "slovenian": "Slowenisch",
    # Ukrainisch
    "uk": "Ukrainisch",
    "ukr": "Ukrainisch",
    "ukrainian": "Ukrainisch",
    # Persisch
    "fa": "Persisch",
    "per": "Persisch",
    "fas": "Persisch",
    "persian": "Persisch",
    # Thailändisch
    "th": "Thailändisch",
    "tha": "Thailändisch",
    "thai": "Thailändisch",
    # Vietnamesisch
    "vi": "Vietnamesisch",
    "vie": "Vietnamesisch",
    "vietnamese": "Vietnamesisch",
    # Indonesisch
    "id": "Indonesisch",
    "ind": "Indonesisch",
    "indonesian": "Indonesisch",
    # Malaiisch
    "ms": "Malaiisch",
    "may": "Malaiisch",
    "msa": "Malaiisch",
    "malay": "Malaiisch",
    # Tagalog
    "tl": "Tagalog",
    "tgl": "Tagalog",
    "tagalog": "Tagalog",
    # Swahili
    "sw": "Swahili",
    "swa": "Swahili",
    "swahili": "Swahili",
    # Hausa
    "ha": "Hausa",
    "hau": "Hausa",
    "hausa": "Hausa",
    # Afrikaans
    "af": "Afrikaans",
    "afr": "Afrikaans",
    "afrikaans": "Afrikaans",
    # Katalanisch
    "ca": "Katalanisch",
    "cat": "Katalanisch",
    "catalan": "Katalanisch",
    # Baskisch
    "eu": "Baskisch",
    "baq": "Baskisch",
    "eus": "Baskisch",
    "basque": "Baskisch",
    # Galizisch
    "gl": "Galizisch",
    "glg": "Galizisch",
    "galician": "Galizisch",
    # Walisisch
    "cy": "Walisisch",
    "wel": "Walisisch",
    "cym": "Walisisch",
    "welsh": "Walisisch",
    # Irisch
    "ga": "Irisch",
    "gle": "Irisch",
    "irish": "Irisch",
    # Schottisch-Gälisch
    "gd": "Schottisch-Gälisch",
    "gla": "Schottisch-Gälisch",
    "scottish gaelic": "Schottisch-Gälisch",
    # Isländisch
    "is": "Isländisch",
    "ice": "Isländisch",
    "isl": "Isländisch",
    "icelandic": "Isländisch",
    # Litauisch
    "lt": "Litauisch",
    "lit": "Litauisch",
    "lithuanian": "Litauisch",
    # Lettisch
    "lv": "Lettisch",
    "lav": "Lettisch",
    "latvian": "Lettisch",
    # Estnisch
    "et": "Estnisch",
    "est": "Estnisch",
    "estonian": "Estnisch",
    # Albanisch
    "sq": "Albanisch",
    "alb": "Albanisch",
    "sqi": "Albanisch",
    "albanian": "Albanisch",
    # Mazedonisch
    "mk": "Mazedonisch",
    "mac": "Mazedonisch",
    "mkd": "Mazedonisch",
    "macedonian": "Mazedonisch",
    # Bosnisch
    "bs": "Bosnisch",
    "bos": "Bosnisch",
    "bosnian": "Bosnisch",
    # Bengalisch
    "bn": "Bengalisch",
    "ben": "Bengalisch",
    "bengali": "Bengalisch",
    # Urdu
    "ur": "Urdu",
    "urd": "Urdu",
    "urdu": "Urdu",
    # Punjabi
    "pa": "Punjabi",
    "pan": "Punjabi",
    "punjabi": "Punjabi",
    # Tamil
    "ta": "Tamil",
    "tam": "Tamil",
    "tamil": "Tamil",
    # Telugu
    "te": "Telugu",
    "tel": "Telugu",
    "telugu": "Telugu",
    # Marathi
    "mr": "Marathi",
    "mar": "Marathi",
    "marathi": "Marathi",
    # Gujarati
    "gu": "Gujarati",
    "guj": "Gujarati",
    "gujarati": "Gujarati",
    # Kannada
    "kn": "Kannada",
    "kan": "Kannada",
    "kannada": "Kannada",
    # Malayalam
    "ml": "Malayalam",
    "mal": "Malayalam",
    "malayalam": "Malayalam",
    # Singhalesisch
    "si": "Singhalesisch",
    "sin": "Singhalesisch",
    "sinhala": "Singhalesisch",
    # Birmanisch
    "my": "Birmanisch",
    "bur": "Birmanisch",
    "mya": "Birmanisch",
    "burmese": "Birmanisch",
    # Khmer
    "km": "Khmer",
    "khm": "Khmer",
    "khmer": "Khmer",
    # Laotisch
    "lo": "Laotisch",
    "lao": "Laotisch",
    "laotian": "Laotisch",
    # Mongolisch
    "mn": "Mongolisch",
    "mon": "Mongolisch",
    "mongolian": "Mongolisch",
    # Nepalesisch
    "ne": "Nepalesisch",
    "nep": "Nepalesisch",
    "nepali": "Nepalesisch",
    # Amharisch
    "am": "Amharisch",
    "amh": "Amharisch",
    "amharic": "Amharisch",
    # Somali
    "so": "Somali",
    "som": "Somali",
    "somali": "Somali",
    # Zulu
    "zu": "Zulu",
    "zul": "Zulu",
    "zulu": "Zulu",
    # Xhosa
    "xh": "Xhosa",
    "xho": "Xhosa",
    "xhosa": "Xhosa",
    # Latein
    "la": "Latein",
    "lat": "Latein",
    "latin": "Latein",
    # Esperanto
    "eo": "Esperanto",
    "epo": "Esperanto",
    "esperanto": "Esperanto",
    # Jiddisch
    "yi": "Jiddisch",
    "yid": "Jiddisch",
    "yiddish": "Jiddisch",
}


LANGUAGE_REVERSE_MAP = {
    "deutsch": ["de", "ger", "deu", "german"],
    "englisch": ["en", "eng", "english"],
    "französisch": ["fr", "fre", "fra", "french"],
    "spanisch": ["es", "spa", "spanish"],
    "italienisch": ["it", "ita", "italian"],
    "niederländisch": ["nl", "dut", "nld", "dutch"],
    "portugiesisch": ["pt", "por", "portuguese"],
    "russisch": ["ru", "rus", "russian"],
    "chinesisch": ["zh", "chi", "zho", "chinese"],
    "japanisch": ["ja", "jpn", "japanese"],
    "koreanisch": ["ko", "kor", "korean"],
    "arabisch": ["ar", "ara", "arabic"],
    "hindi": ["hi", "hin", "hindi"],
    "polnisch": ["pl", "pol", "polish"],
    "türkisch": ["tr", "tur", "turkish"],
    "schwedisch": ["sv", "swe", "swedish"],
    "norwegisch": ["no", "nor", "norwegian"],
    "dänisch": ["da", "dan", "danish"],
    "finnisch": ["fi", "fin", "finnish"],
    "griechisch": ["el", "gre", "ell", "greek"],
    "hebräisch": ["he", "heb", "hebrew"],
    "tschechisch": ["cs", "ces", "cze", "czech"],
    "ungarisch": ["hu", "hun", "hungarian"],
    "rumänisch": ["ro", "ron", "rum", "romanian"],
}


TOPICS = {
    "love": {"name_de": "Liebe", "name_en": "Love"},
    "war": {"name_de": "Krieg", "name_en": "War"},
    "politics": {"name_de": "Politik", "name_en": "Politics"},
    "psychology": {"name_de": "Psychologie", "name_en": "Psychology"},
    "education": {"name_de": "Bildung", "name_en": "Education"},
    "economy": {"name_de": "Ökonomie", "name_en": "Economy"},
    "medicine": {"name_de": "Medizin", "name_en": "Medicine"},
    "law": {"name_de": "Recht", "name_en": "Law"},
    "music": {"name_de": "Musik", "name_en": "Music"},
    "film": {"name_de": "Film", "name_en": "Film"},
    "literature": {"name_de": "Literatur", "name_en": "Literature"},
    "poetry": {"name_de": "Lyrik", "name_en": "Poetry"},
    "drama": {"name_de": "Drama", "name_en": "Drama"},
    "nature": {"name_de": "Natur", "name_en": "Nature"},
    "environment": {"name_de": "Umwelt", "name_en": "Environment"},
    "physics": {"name_de": "Physik", "name_en": "Physics"},
    "chemistry": {"name_de": "Chemie", "name_en": "Chemistry"},
    "mathematics": {"name_de": "Mathematik", "name_en": "Mathematics"},
    "computer_science": {"name_de": "Informatik", "name_en": "Computer Science"},
    "ai": {"name_de": "Künstliche Intelligenz", "name_en": "Artificial Intelligence"},
    "football": {"name_de": "Fußball", "name_en": "Football"},
    "family": {"name_de": "Familie", "name_en": "Family"},
    "friendship": {"name_de": "Freundschaft", "name_en": "Friendship"},
    "crime": {"name_de": "Krimi", "name_en": "Crime"},
    "fantasy": {"name_de": "Fantasy", "name_en": "Fantasy"},
    "science_fiction": {"name_de": "Science Fiction", "name_en": "Science Fiction"},
    "thriller": {"name_de": "Thriller", "name_en": "Thriller"},
    "romance": {"name_de": "Romantik", "name_en": "Romance"},
    "horror": {"name_de": "Horror", "name_en": "Horror"},
    "mystery": {"name_de": "Mystery", "name_en": "Mystery"},
}


CATEGORY_TO_GENRE = {
    "fiction": "fiction",
    "belletristik": "fiction",
    "roman": "fiction",
    "literature": "fiction",
    "literary fiction": "fiction",
    "novels": "fiction",
    "non-fiction": "non_fiction",
    "nonfiction": "non_fiction",
    "sachbuch": "non_fiction",
    "biography": "biography",
    "biografie": "biography",
    "autobiography": "biography",
    "autobiographie": "biography",
    "memoir": "biography",
    "history": "history",
    "geschichte": "history",
    "historical": "history",
    "philosophy": "philosophy",
    "philosophie": "philosophy",
    "psychology": "psychology",
    "psychologie": "psychology",
    "language arts": "non_fiction",
    "language arts & disciplines": "non_fiction",
    "linguistics": "non_fiction",
    "science": "science",
    "wissenschaft": "science",
    "natural science": "science",
    "technology": "technology",
    "technik": "technology",
    "computers": "technology",
    "computer science": "technology",
    "arts": "arts",
    "kunst": "arts",
    "music": "arts",
    "musik": "arts",
    "painting": "arts",
    "sports": "sports",
    "sport": "sports",
    "travel": "travel",
    "reise": "travel",
    "cooking": "cooking",
    "kochen": "cooking",
    "recipes": "cooking",
    "self-help": "self_help",
    "ratgeber": "self_help",
    "self help": "self_help",
    "religion": "religion",
    "religious": "religion",
    "business": "business",
    "wirtschaft": "business",
    "economics": "business",
    "management": "business",
    "children": "children",
    "kinderbuch": "children",
    "juvenile": "children",
    "young adult": "children",
}


CATEGORY_TO_TOPIC = {
    "love": "love",
    "liebe": "love",
    "romance": "romance",
    "romantik": "romance",
    "romantic": "romance",
    "war": "war",
    "krieg": "war",
    "warfare": "war",
    "politics": "politics",
    "politik": "politics",
    "political": "politics",
    "psychology": "psychology",
    "psychologie": "psychology",
    "psychological": "psychology",
    "family": "family",
    "familie": "family",
    "friendship": "friendship",
    "freundschaft": "friendship",
    "crime": "crime",
    "krimi": "crime",
    "criminal": "crime",
    "thriller": "thriller",
    "suspense": "thriller",
    "fantasy": "fantasy",
    "science fiction": "science_fiction",
    "sci-fi": "science_fiction",
    "scifi": "science_fiction",
    "horror": "horror",
    "mystery": "mystery",
    "detective": "mystery",
    "nature": "nature",
    "natur": "nature",
    "environment": "environment",
    "umwelt": "environment",
    "environmental": "environment",
    "medicine": "medicine",
    "medizin": "medicine",
    "medical": "medicine",
    "law": "law",
    "recht": "law",
    "legal": "law",
    "education": "education",
    "bildung": "education",
    "educational": "education",
    "football": "football",
    "fußball": "football",
    "soccer": "football",
    "music": "music",
    "musik": "music",
    "musical": "music",
    "film": "film",
    "cinema": "film",
    "movies": "film",
    "poetry": "poetry",
    "lyrik": "poetry",
    "poems": "poetry",
    "drama": "drama",
    "dramatic": "drama",
    "physics": "physics",
    "physik": "physics",
    "chemistry": "chemistry",
    "chemie": "chemistry",
    "mathematics": "mathematics",
    "mathematik": "mathematics",
    "math": "mathematics",
    "economy": "economy",
    "ökonomie": "economy",
    "economic": "economy",
    "artificial intelligence": "ai",
    "künstliche intelligenz": "ai",
    "machine learning": "ai",
}
